name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki).
version: 0.4.3
homepage: https://github.com/hpoul/dart_logging_appenders/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  http: ^0.13.3
  logging: ^1.0.2
  meta: ^1.7.0


dev_dependencies:
  fake_async: ^1.2.0
  mockito: ^5.0.16
  path: ^1.8.0
  pedantic: ^1.11.1
  test: ^1.17.12

dependency_overrides:
  pedantic: ^1.8.0+1
